### ISSUE TITLE
No such file or directory: 'pretrain/pe_checkpoint.pth'  

### ISSUE THREAD

**Issue by mwdotzom** [qcraftai/gedepth#3]
Hi, where should I find this weight file when training ddad_v?
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/pe_checkpoint.pth'  
https://github.com/qcraftai/gedepth/blob/main/tools/train.py#L66

**Comment by RobinhoodKi** [comment]
Hi, Thank you for your advise! We've uploaded the ckpt on Google Drive and Baidu Cloud.
Feel free to contact us if you need any help.

**Comment by mwdotzom** [comment]
Could you double check google drive? I can't find the file there yet, thx!

**Comment by RobinhoodKi** [comment]
Can you check again ?
